# Generated by Django 4.2.7 on 2024-05-23 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passchem_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, null=True, upload_to='unit_images')),
                ('unit_number', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='document',
            new_name='worksheet',
        ),
        migrations.AddField(
            model_name='lesson',
            name='notes',
            field=models.FileField(blank=True, null=True, upload_to='documents/notes'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passchem_api.unit')),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passchem_api.topic'),
        ),
        migrations.DeleteModel(
            name='Topics',
        ),
    ]
