# Generated by Django 4.2.7 on 2024-05-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passchem_api', '0002_unit_rename_document_lesson_worksheet_lesson_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
