# Generated by Django 4.2.7 on 2024-05-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passchem_api', '0003_lesson_lesson_number_topic_topic_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolanguage',
            name='language_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
