# Generated by Django 4.2.7 on 2024-05-27 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passchem_api', '0006_userlesson'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoLanguage',
            new_name='VideoSetting',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='passchem_api.topic'),
        ),
    ]
