# Generated by Django 4.2.7 on 2024-08-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passchem_api', '0009_alter_topic_unit_userunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
