# Generated by Django 4.2.7 on 2024-01-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_alter_topics_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='image',
        ),
        migrations.AddField(
            model_name='topics',
            name='img',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
