# Generated by Django 4.2.7 on 2024-01-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_remove_topics_image_topics_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='img',
            field=models.ImageField(null=True, upload_to='topics_images'),
        ),
    ]
