# Generated by Django 4.2.7 on 2024-02-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_alter_topics_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='documents',
        ),
        migrations.AddField(
            model_name='lesson',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/worksheets'),
        ),
    ]
