# Generated by Django 4.2.7 on 2024-03-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_remove_lesson_documents_lesson_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
