# Generated by Django 4.2.7 on 2024-03-05 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_videolanguage_remove_lesson_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolanguage',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topics.lesson'),
        ),
    ]
