# Generated by Django 4.2.7 on 2024-03-08 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_videolanguage_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolanguage',
            name='url',
        ),
        migrations.AddField(
            model_name='videolanguage',
            name='url_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='videolanguage',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.lesson'),
        ),
    ]
