# Generated by Django 4.2.7 on 2024-03-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_alter_videolanguage_url_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='answer_key',
            field=models.FileField(blank=True, null=True, upload_to='documents/answer_keys'),
        ),
    ]
