# Generated by Django 4.2.7 on 2024-08-08 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_email_verified_user_google_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
