# Generated by Django 4.2.7 on 2024-08-15 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
